engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  fixme:
    enabled: true
ratings:
  paths:
    - "src/**/*"
    - "scripts/**/*"
    - "views/**/*"
exclude_paths:
 - "docs/**/*"
 - "**/jquery*"
 - "**/bootstrap*"
 - "public_static/**/*"
