language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules
    
# services: postgresql

install:
  - npm install -D
  - npm install -D codecov

script:
  - npm run test

after_success:
  - npm run codecov
